version: "3.7"
services:
  python-dev:
    entrypoint: /bin/bash
    build: .
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: python-app
        target: /python-app
volumes: 
  python-app:
    name: python-app