version: "3.7"
services:
  python-dev:
    entrypoint: /bin/bash
    build: .
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: app
        target: /app
volumes: 
  app:
    name: app